cd C:.Users.vm.Documents.GitHub

python.exe C:\Python27\Lib\pydoc.py -w fortrace.common
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.browser
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.config
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.constants
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.exceptions
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.ipaddr
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.macAddr
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.mailer
python.exe C:\Python27\Lib\pydoc.py -w fortrace.common.network
python.exe C:\Python27\Lib\pydoc.py -w fortrace.core
python.exe C:\Python27\Lib\pydoc.py -w fortrace.core.vm
python.exe C:\Python27\Lib\pydoc.py -w fortrace.core.vmHelper
python.exe C:\Python27\Lib\pydoc.py -w fortrace.examples.destroyNetworks
python.exe C:\Python27\Lib\pydoc.py -w fortrace.examples.fortracemanager
python.exe C:\Python27\Lib\pydoc.py -w fortrace.examples.interaktionsmanagerWindows
python.exe C:\Python27\Lib\pydoc.py -w fortrace.examples.setupNetworks
python.exe C:\Python27\Lib\pydoc.py -w fortrace.examples
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.linux
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.linux.interactionManager
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.linux.xaut
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.utilities
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.utilities._sendkeys
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.utilities.seleniumkeys
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.utilities.SendKeys
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.utilities
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.inputDevice
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.keyboard
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.inputDevice.mouse
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.application
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.application.application
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.application.instantMessenger
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.application.mailClient
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.application.webBrowser
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.application
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.interactionmanager
python.exe C:\Python27\Lib\pydoc.py -w fortrace.interactionManager.windows.window
python.exe C:\Python27\Lib\pydoc.py -w fortrace