
imagename = "smbScenario"
author = "David Konczewski"
hostplatform = "windows"
poolpath = "/home/wurstfingersalat/Downloads/fortracepool/"
smbname = "smbServer"
smbplatform = "unix"
sourcePath = "C:\Users\fortrace\Desktop\TestFile.txt"
targetPath = r"\\192.168.103.102\public"
username = "bla"
password = "test"
