# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcemessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='announcemessage.proto',
  package='',
  serialized_pb='\n\x15\x61nnouncemessage.proto\x1a\x14genericmessage.proto\"C\n\x0c\x41nnounceInfo\x12\x1e\n\x05state\x18\x01 \x02(\x0e\x32\x0f.AnnounceStatus\x12\x13\n\x0binstance_of\x18\x02 \x02(\t*]\n\x0e\x41nnounceStatus\x12\x13\n\x0fONLINE_DISABLED\x10\x00\x12\x12\n\x0eONLINE_ENABLED\x10\x01\x12\x15\n\x11GRACEFUL_SHUTDOWN\x10\x02\x12\x0b\n\x07\x43RASHED\x10\x03:3\n\x0bstatus_info\x12\x0f.GenericMessage\x18\x64 \x02(\x0b\x32\r.AnnounceInfo')

_ANNOUNCESTATUS = _descriptor.EnumDescriptor(
  name='AnnounceStatus',
  full_name='AnnounceStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONLINE_DISABLED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE_ENABLED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRACEFUL_SHUTDOWN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRASHED', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=116,
  serialized_end=209,
)

AnnounceStatus = enum_type_wrapper.EnumTypeWrapper(_ANNOUNCESTATUS)
ONLINE_DISABLED = 0
ONLINE_ENABLED = 1
GRACEFUL_SHUTDOWN = 2
CRASHED = 3

STATUS_INFO_FIELD_NUMBER = 100
status_info = _descriptor.FieldDescriptor(
  name='status_info', full_name='status_info', index=0,
  number=100, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ANNOUNCEINFO = _descriptor.Descriptor(
  name='AnnounceInfo',
  full_name='AnnounceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='AnnounceInfo.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_of', full_name='AnnounceInfo.instance_of', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=114,
)

_ANNOUNCEINFO.fields_by_name['state'].enum_type = _ANNOUNCESTATUS
DESCRIPTOR.message_types_by_name['AnnounceInfo'] = _ANNOUNCEINFO

class AnnounceInfo(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _ANNOUNCEINFO

  # @@protoc_insertion_point(class_scope:AnnounceInfo)

status_info.message_type = _ANNOUNCEINFO
genericmessage_pb2.GenericMessage.RegisterExtension(status_info)

# @@protoc_insertion_point(module_scope)
