# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: answermessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='answermessage.proto',
  package='',
  serialized_pb='\n\x13\x61nswermessage.proto\x1a\x14genericmessage.proto\"?\n\nAnswerInfo\x12\x10\n\x02ok\x18\x01 \x02(\x08:\x04true\x12\x0f\n\x07request\x18\x02 \x02(\x0c\x12\x0e\n\x06\x61nswer\x18\x03 \x02(\t:1\n\x0b\x61nswer_info\x12\x0f.GenericMessage\x18k \x02(\x0b\x32\x0b.AnswerInfo')


ANSWER_INFO_FIELD_NUMBER = 107
answer_info = _descriptor.FieldDescriptor(
  name='answer_info', full_name='answer_info', index=0,
  number=107, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ANSWERINFO = _descriptor.Descriptor(
  name='AnswerInfo',
  full_name='AnswerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='AnswerInfo.ok', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='AnswerInfo.request', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='AnswerInfo.answer', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['AnswerInfo'] = _ANSWERINFO

class AnswerInfo(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _ANSWERINFO

  # @@protoc_insertion_point(class_scope:AnswerInfo)

answer_info.message_type = _ANSWERINFO
genericmessage_pb2.GenericMessage.RegisterExtension(answer_info)

# @@protoc_insertion_point(module_scope)
