# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: botmastermessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='botmastermessage.proto',
  package='',
  serialized_pb='\n\x16\x62otmastermessage.proto\x1a\x14genericmessage.proto\"5\n\x1a\x42otMasterPlaceOrderMessage\x12\x17\n\x0fserialized_dict\x18\x01 \x02(\x0c\"E\n\x13\x42otMasterGetResults\x12\x16\n\x0ereceiving_host\x18\x01 \x02(\t\x12\x16\n\x0ereceiving_port\x18\x02 \x02(\r:?\n\x08\x62m_order\x12\x0f.GenericMessage\x18\xdc\x01 \x02(\x0b\x32\x1b.BotMasterPlaceOrderMessage:9\n\tbm_result\x12\x0f.GenericMessage\x18\xdd\x01 \x02(\x0b\x32\x14.BotMasterGetResults')


BM_ORDER_FIELD_NUMBER = 220
bm_order = _descriptor.FieldDescriptor(
  name='bm_order', full_name='bm_order', index=0,
  number=220, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
BM_RESULT_FIELD_NUMBER = 221
bm_result = _descriptor.FieldDescriptor(
  name='bm_result', full_name='bm_result', index=1,
  number=221, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_BOTMASTERPLACEORDERMESSAGE = _descriptor.Descriptor(
  name='BotMasterPlaceOrderMessage',
  full_name='BotMasterPlaceOrderMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialized_dict', full_name='BotMasterPlaceOrderMessage.serialized_dict', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=101,
)


_BOTMASTERGETRESULTS = _descriptor.Descriptor(
  name='BotMasterGetResults',
  full_name='BotMasterGetResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiving_host', full_name='BotMasterGetResults.receiving_host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receiving_port', full_name='BotMasterGetResults.receiving_port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['BotMasterPlaceOrderMessage'] = _BOTMASTERPLACEORDERMESSAGE
DESCRIPTOR.message_types_by_name['BotMasterGetResults'] = _BOTMASTERGETRESULTS

class BotMasterPlaceOrderMessage(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _BOTMASTERPLACEORDERMESSAGE

  # @@protoc_insertion_point(class_scope:BotMasterPlaceOrderMessage)

class BotMasterGetResults(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _BOTMASTERGETRESULTS

  # @@protoc_insertion_point(class_scope:BotMasterGetResults)

bm_order.message_type = _BOTMASTERPLACEORDERMESSAGE
genericmessage_pb2.GenericMessage.RegisterExtension(bm_order)
bm_result.message_type = _BOTMASTERGETRESULTS
genericmessage_pb2.GenericMessage.RegisterExtension(bm_result)

# @@protoc_insertion_point(module_scope)
