# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: botmessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='botmessage.proto',
  package='',
  serialized_pb='\n\x10\x62otmessage.proto\x1a\x14genericmessage.proto\":\n\x14\x42otPullOrdersMessage\x12\x10\n\x08src_host\x18\x01 \x01(\t\x12\x10\n\x08src_port\x18\x02 \x01(\r:9\n\x08\x62ot_pull\x12\x0f.GenericMessage\x18\xd2\x01 \x02(\x0b\x32\x15.BotPullOrdersMessage')


BOT_PULL_FIELD_NUMBER = 210
bot_pull = _descriptor.FieldDescriptor(
  name='bot_pull', full_name='bot_pull', index=0,
  number=210, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_BOTPULLORDERSMESSAGE = _descriptor.Descriptor(
  name='BotPullOrdersMessage',
  full_name='BotPullOrdersMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_host', full_name='BotPullOrdersMessage.src_host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='BotPullOrdersMessage.src_port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['BotPullOrdersMessage'] = _BOTPULLORDERSMESSAGE

class BotPullOrdersMessage(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _BOTPULLORDERSMESSAGE

  # @@protoc_insertion_point(class_scope:BotPullOrdersMessage)

bot_pull.message_type = _BOTPULLORDERSMESSAGE
genericmessage_pb2.GenericMessage.RegisterExtension(bot_pull)

# @@protoc_insertion_point(module_scope)
