# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cncmessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cncmessage.proto',
  package='',
  serialized_pb='\n\x10\x63ncmessage.proto\x1a\x14genericmessage.proto\"2\n\x14\x43nCPushOrdersMessage\x12\x0c\n\x04host\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\r\"&\n\x14\x43nCHostOrdersMessage\x12\x0e\n\x06orders\x18\x01 \x02(\x0c:9\n\x08\x63nc_push\x12\x0f.GenericMessage\x18\xc8\x01 \x02(\x0b\x32\x15.CnCPushOrdersMessage:9\n\x08\x63nc_host\x12\x0f.GenericMessage\x18\xc9\x01 \x02(\x0b\x32\x15.CnCHostOrdersMessage')


CNC_PUSH_FIELD_NUMBER = 200
cnc_push = _descriptor.FieldDescriptor(
  name='cnc_push', full_name='cnc_push', index=0,
  number=200, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
CNC_HOST_FIELD_NUMBER = 201
cnc_host = _descriptor.FieldDescriptor(
  name='cnc_host', full_name='cnc_host', index=1,
  number=201, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_CNCPUSHORDERSMESSAGE = _descriptor.Descriptor(
  name='CnCPushOrdersMessage',
  full_name='CnCPushOrdersMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='CnCPushOrdersMessage.host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='CnCPushOrdersMessage.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=92,
)


_CNCHOSTORDERSMESSAGE = _descriptor.Descriptor(
  name='CnCHostOrdersMessage',
  full_name='CnCHostOrdersMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='CnCHostOrdersMessage.orders', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['CnCPushOrdersMessage'] = _CNCPUSHORDERSMESSAGE
DESCRIPTOR.message_types_by_name['CnCHostOrdersMessage'] = _CNCHOSTORDERSMESSAGE

class CnCPushOrdersMessage(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _CNCPUSHORDERSMESSAGE

  # @@protoc_insertion_point(class_scope:CnCPushOrdersMessage)

class CnCHostOrdersMessage(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _CNCHOSTORDERSMESSAGE

  # @@protoc_insertion_point(class_scope:CnCHostOrdersMessage)

cnc_push.message_type = _CNCPUSHORDERSMESSAGE
genericmessage_pb2.GenericMessage.RegisterExtension(cnc_push)
cnc_host.message_type = _CNCHOSTORDERSMESSAGE
genericmessage_pb2.GenericMessage.RegisterExtension(cnc_host)

# @@protoc_insertion_point(module_scope)
