# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genericmessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
# @@protoc_insertion_point(imports)


from . import messagetypes_pb2
import six

DESCRIPTOR = _descriptor.FileDescriptor(
  name='genericmessage.proto',
  package='',
  serialized_pb='\n\x14genericmessage.proto\x1a\x12messagetypes.proto\"y\n\x0eGenericMessage\x12\"\n\x0cmessage_type\x18\x01 \x02(\x0e\x32\x0c.MessageType\x12\x12\n\nmessage_id\x18\x02 \x02(\x04\x12\x1d\n\x0erequest_answer\x18\x03 \x01(\x08:\x05\x66\x61lse*\x05\x08\x64\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02P\x00')




_GENERICMESSAGE = _descriptor.Descriptor(
  name='GenericMessage',
  full_name='GenericMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='GenericMessage.message_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='GenericMessage.message_id', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_answer', full_name='GenericMessage.request_answer', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 2000), (2000, 536870912), ],
  serialized_start=44,
  serialized_end=165,
)

_GENERICMESSAGE.fields_by_name['message_type'].enum_type = messagetypes_pb2._MESSAGETYPE
DESCRIPTOR.message_types_by_name['GenericMessage'] = _GENERICMESSAGE

class GenericMessage(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _GENERICMESSAGE

  # @@protoc_insertion_point(class_scope:GenericMessage)


# @@protoc_insertion_point(module_scope)
