# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genericdatamessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='genericdatamessage.proto',
  package='',
  serialized_pb='\n\x18genericdatamessage.proto\x1a\x14genericmessage.proto\"\x1e\n\x0bGenericData\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\x0c:+\n\x04\x64\x61ta\x12\x0f.GenericMessage\x18l \x02(\x0b\x32\x0c.GenericData')


DATA_FIELD_NUMBER = 108
data = _descriptor.FieldDescriptor(
  name='data', full_name='data', index=0,
  number=108, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_GENERICDATA = _descriptor.Descriptor(
  name='GenericData',
  full_name='GenericData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='GenericData.content', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['GenericData'] = _GENERICDATA

class GenericData(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _GENERICDATA

  # @@protoc_insertion_point(class_scope:GenericData)

data.message_type = _GENERICDATA
genericmessage_pb2.GenericMessage.RegisterExtension(data)

# @@protoc_insertion_point(module_scope)
