# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logmessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='logmessage.proto',
  package='',
  serialized_pb='\n\x10logmessage.proto\x1a\x14genericmessage.proto\"G\n\x07LogInfo\x12\x1b\n\x08severity\x18\x01 \x02(\x0e\x32\t.Severity\x12\x0e\n\x06source\x18\x02 \x02(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x02(\t*K\n\x08Severity\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x11\n\rINFORMATIONAL\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04:+\n\x08log_info\x12\x0f.GenericMessage\x18h \x02(\x0b\x32\x08.LogInfo')

_SEVERITY = _descriptor.EnumDescriptor(
  name='Severity',
  full_name='Severity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFORMATIONAL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=115,
  serialized_end=190,
)

Severity = enum_type_wrapper.EnumTypeWrapper(_SEVERITY)
OK = 0
DEBUG = 1
INFORMATIONAL = 2
WARNING = 3
CRITICAL = 4

LOG_INFO_FIELD_NUMBER = 104
log_info = _descriptor.FieldDescriptor(
  name='log_info', full_name='log_info', index=0,
  number=104, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_LOGINFO = _descriptor.Descriptor(
  name='LogInfo',
  full_name='LogInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='severity', full_name='LogInfo.severity', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='LogInfo.source', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='LogInfo.context', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=113,
)

_LOGINFO.fields_by_name['severity'].enum_type = _SEVERITY
DESCRIPTOR.message_types_by_name['LogInfo'] = _LOGINFO

class LogInfo(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _LOGINFO

  # @@protoc_insertion_point(class_scope:LogInfo)

log_info.message_type = _LOGINFO
genericmessage_pb2.GenericMessage.RegisterExtension(log_info)

# @@protoc_insertion_point(module_scope)
