# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagetypes.proto

from __future__ import absolute_import
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messagetypes.proto',
  package='',
  serialized_pb='\n\x12messagetypes.proto*\xd6\x02\n\x0bMessageType\x12\t\n\x05\x44UMMY\x10\x00\x12\x0c\n\x08\x41NNOUNCE\x10\x01\x12\x0c\n\x08\x41\x43TIVATE\x10\x02\x12\x0b\n\x07\x44ISABLE\x10\x03\x12\r\n\tTERMINATE\x10\x04\x12\x07\n\x03LOG\x10\x05\x12\x13\n\x0fPAYLOAD_REQUEST\x10\x06\x12\x0b\n\x07PAYLOAD\x10\x07\x12\n\n\x06\x41NSWER\x10\x08\x12\x13\n\x0fGLOBALS_REQUEST\x10\t\x12\x12\n\x0eGLOBALS_ANSWER\x10\n\x12\x0b\n\x07\x42OTPULL\x10\x32\x12\x0e\n\nBOTEXECUTE\x10\x33\x12\x11\n\rCNCPUSHORDERS\x10<\x12\x16\n\x12\x43NCBROADCASTORDERS\x10=\x12\x11\n\rCNCHOSTORDERS\x10>\x12\x17\n\x13\x42OTMASTERPLACEORDER\x10\x46\x12\x16\n\x12\x42OTMASTERGETRESULT\x10G\x12\x18\n\x13SAMPLEEXTENSIONTYPE\x10\xd0\x0f')

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOUNCE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVATE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISABLE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TERMINATE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOG', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_REQUEST', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANSWER', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOBALS_REQUEST', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOBALS_ANSWER', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOTPULL', index=11, number=50,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOTEXECUTE', index=12, number=51,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CNCPUSHORDERS', index=13, number=60,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CNCBROADCASTORDERS', index=14, number=61,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CNCHOSTORDERS', index=15, number=62,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOTMASTERPLACEORDER', index=16, number=70,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOTMASTERGETRESULT', index=17, number=71,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAMPLEEXTENSIONTYPE', index=18, number=2000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=23,
  serialized_end=365,
)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
DUMMY = 0
ANNOUNCE = 1
ACTIVATE = 2
DISABLE = 3
TERMINATE = 4
LOG = 5
PAYLOAD_REQUEST = 6
PAYLOAD = 7
ANSWER = 8
GLOBALS_REQUEST = 9
GLOBALS_ANSWER = 10
BOTPULL = 50
BOTEXECUTE = 51
CNCPUSHORDERS = 60
CNCBROADCASTORDERS = 61
CNCHOSTORDERS = 62
BOTMASTERPLACEORDER = 70
BOTMASTERGETRESULT = 71
SAMPLEEXTENSIONTYPE = 2000




# @@protoc_insertion_point(module_scope)
