# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloadmessage.proto

from __future__ import absolute_import
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)


from . import genericmessage_pb2
import six


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payloadmessage.proto',
  package='',
  serialized_pb='\n\x14payloadmessage.proto\x1a\x14genericmessage.proto\"/\n\x0ePayloadRequest\x12\x1d\n\x0cpayload_name\x18\x01 \x02(\t:\x07\x64\x65\x66\x61ult\"^\n\x0bPayloadInfo\x12 \n\x0bsource_type\x18\x01 \x02(\x0e\x32\x0b.SourceType\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c*-\n\nSourceType\x12\x0c\n\x08\x45MBEDDED\x10\x00\x12\x08\n\x04HTTP\x10\x01\x12\x07\n\x03\x46TP\x10\x02:3\n\x0cpayload_info\x12\x0f.GenericMessage\x18i \x02(\x0b\x32\x0c.PayloadInfo:5\n\x0bpayload_req\x12\x0f.GenericMessage\x18j \x02(\x0b\x32\x0f.PayloadRequest')

_SOURCETYPE = _descriptor.EnumDescriptor(
  name='SourceType',
  full_name='SourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMBEDDED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FTP', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=191,
  serialized_end=236,
)

SourceType = enum_type_wrapper.EnumTypeWrapper(_SOURCETYPE)
EMBEDDED = 0
HTTP = 1
FTP = 2

PAYLOAD_INFO_FIELD_NUMBER = 105
payload_info = _descriptor.FieldDescriptor(
  name='payload_info', full_name='payload_info', index=0,
  number=105, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
PAYLOAD_REQ_FIELD_NUMBER = 106
payload_req = _descriptor.FieldDescriptor(
  name='payload_req', full_name='payload_req', index=1,
  number=106, type=11, cpp_type=10, label=2,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PAYLOADREQUEST = _descriptor.Descriptor(
  name='PayloadRequest',
  full_name='PayloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_name', full_name='PayloadRequest.payload_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=six.text_type("default", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=93,
)


_PAYLOADINFO = _descriptor.Descriptor(
  name='PayloadInfo',
  full_name='PayloadInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_type', full_name='PayloadInfo.source_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='PayloadInfo.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=six.text_type("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='PayloadInfo.size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='PayloadInfo.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=189,
)

_PAYLOADINFO.fields_by_name['source_type'].enum_type = _SOURCETYPE
DESCRIPTOR.message_types_by_name['PayloadRequest'] = _PAYLOADREQUEST
DESCRIPTOR.message_types_by_name['PayloadInfo'] = _PAYLOADINFO

class PayloadRequest(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _PAYLOADREQUEST

  # @@protoc_insertion_point(class_scope:PayloadRequest)

class PayloadInfo(six.with_metaclass(_reflection.GeneratedProtocolMessageType, _message.Message)):
  DESCRIPTOR = _PAYLOADINFO

  # @@protoc_insertion_point(class_scope:PayloadInfo)

payload_info.message_type = _PAYLOADINFO
genericmessage_pb2.GenericMessage.RegisterExtension(payload_info)
payload_req.message_type = _PAYLOADREQUEST
genericmessage_pb2.GenericMessage.RegisterExtension(payload_req)

# @@protoc_insertion_point(module_scope)
